examples/bundle/1-ZuweisungZurRadiologischenDiagnostik-FHIR.xml, examples/composition/ZuweisungZurRadiologischenDiagnostik.xml, examples/organization/GruppenpraxisCH.xml, examples/organization/Radiologieinstitut.xml, examples/patient/MaxMuster.xml, examples/practitioner/SchreibKraft.xml, examples/upload.http, resources/implementationguide/ch.fhir.ig.ch-core.xml, resources/structuredefinition/ch-core-composition-epr.xml, resources/structuredefinition/ch-core-composition.xml, resources/structuredefinition/ch-core-document.xml, resources/structuredefinition/ch-core-documentreference-epr.xml, resources/structuredefinition/ch-core-organization-epr.xml, resources/structuredefinition/ch-core-organization.xml, resources/structuredefinition/ch-core-patient-epr.xml, resources/structuredefinition/ch-core-patient.xml, resources/structuredefinition/ch-core-practitioner-epr.xml, resources/structuredefinition/ch-ext-epr-confidentialitycode.xml, resources/structuredefinition/ch-ext-epr-dataenterer.xml, resources/structuredefinition/ch-ext-epr-informationrecipient.xml, resources/structuredefinition/ch-ext-epr-setid.xml, resources/structuredefinition/ch-ext-epr-versionnumber.xml
add epr-profile, based on the core-profiles for:
- Composition
- Patient
- Practitioner
- Organization
=> added epr-profiles (based on core-profiles)

input/resources/structuredefinition/ch-core-organization.xml
see https://github.com/hl7ch/ch-core/issues/60
=> adjust cardinality according to #60

input/examples/patient/ElisabethBroennimannByBFH.xml, input/examples/patient/FranzMuster.xml, input/examples/practitioner/HanspeterWengerByBFH.xml, input/resources/namingsystem/ahvn13-navs13.xml, input/resources/namingsystem/epr-spid.xml, input/resources/namingsystem/gln.xml, input/resources/namingsystem/zsr.xml
see https://github.com/hl7ch/ch-core/issues/70
=> fix resource narrative

input/resources/structuredefinition/ch-core-encounter.xml
https://github.com/hl7ch/ch-core/issues/58
=> fix typos for #58

input/resources/structuredefinition/ch-core-composition-epr.xml
https://github.com/hl7ch/ch-core/issues/57
=> epr composition adjust card. #57

input/examples/practitioner/AllzeitBereit.xml, input/examples/practitioner/HanspeterWengerByBFH.xml, input/resources/structuredefinition/ch-core-humanname.xml
https://github.com/hl7ch/ch-core/issues/42
=> add example for legalstatus in prefix/humanname

input/ch.fhir.ig.ch-core.xml, input/examples/patient/PersonEch011.xml, input/resources/codesystem/ech-11-maritaldata-separation.xml, input/resources/structuredefinition/ch-ext-ech-11-maritaldata-separation.xml, input/resources/valueset/ech-11-maritaldata-separation.xml
see https://github.com/hl7ch/ch-core/issues/35
=> adding maritaldata-separation

input/ch.fhir.ig.ch-core.xml, input/examples/encounter/EncounterAccidentBroennimann.xml, input/resources/structuredefinition/ch-core-encounter.xml, input/resources/structuredefinition/ch-ext-accident.xml
https://github.com/hl7ch/ch-core/issues/41
=> Unfallkennzeichen und Unfalldatum

input/ch.fhir.ig.ch-core.xml, input/examples/encounter/EncounterAccidentBroennimann.xml, input/resources/structuredefinition/ch-core-encounter.xml, input/resources/structuredefinition/ch-ext-encounter-susp-readmission.xml
https://github.com/hl7ch/ch-core/issues/40
=> #40 suspected readmission

input/pagecontent/index.md
added cc0 license like fhir spec and use lectored text as submitted to eCH
=> #67 license and corrected text

input/resources/codesystem/ech-11-maritaldata-separation.xml, input/resources/structuredefinition/ch-core-patient.xml, input/resources/structuredefinition/ch-ext-ech-11-maritaldata-separation.xml, input/resources/valueset/ech-11-maritaldata-separation.xml
=> harmonize word., adding extension to maritalStatus

input/ch.fhir.ig.ch-core.xml, input/examples/consent/EncounterExcludedForEpr.json, input/examples/consent/PatientHasEpr.json, input/resources/structuredefinition/ch-core-consent-epr.xml
Add EPR consent profile to CH-Core.
The code is requested as a PR to the UTG project: https://jira.hl7.org/browse/UP-163
=> Epr consent

input/resources/structuredefinition/ch-core-composition-epr.xml
=> set minimum cardinality to 1

input/ch.fhir.ig.ch-core.xml, input/examples/organization/SpitalSeeblick.xml, input/examples/patient/UpiEprTestKrcmarevic.xml, input/pages/changelog.md, input/resources/structuredefinition/ch-core-epr-spid-identifier.xml, input/resources/structuredefinition/ch-core-gln-identifier.xml, input/resources/structuredefinition/ch-core-organization.xml, input/resources/structuredefinition/ch-core-patient.xml, input/resources/structuredefinition/ch-core-practitioner.xml
add gln and epr-spid checks (digit, length, start) see #123
=> check digits for gln and epr-spid #123

input/pages/changelog.md, input/resources/structuredefinition/ch-core-encounter.xml
Update link and check locally with dependency `dev`: see link in definition of [Encounter.class](http://build.fhir.org/ig/hl7ch/ch-core/branches/issue132/StructureDefinition-ch-core-encounter-definitions.html#Encounter.class)
(Note: `ConceptMap-bfs-encounter-class-to-fhir.html` didn't work)
=> update link (issue #132)

input/pages/changelog.md, input/resources/structuredefinition/ch-core-document-epr.xml, input/resources/structuredefinition/ch-core-document.xml
@oliveregger 
Bitte um Review. Ich habe die Basiselemente (wie Patient, Practitioner) in CH Core umgesetzt und dann lokal (dev dependency) mit CH EMED (zusätzlich MedicationStatement etc.)  getestet, Warnungen sind dann weg.
=> improve slicing (issue #144)

input/pages/changelog.md, input/resources/structuredefinition/ch-core-practitioner.xml
fixed according decision for #124 
https://build.fhir.org/ig/hl7ch/ch-core/branches/issue124/StructureDefinition-ch-core-practitioner.html
=> fix description for HumaneName constraint #124

input/pages/changelog.md, input/resources/structuredefinition/ch-ext-epr-time.xml
updated extension: http://build.fhir.org/ig/hl7ch/ch-core/branches/issue150/StructureDefinition-ch-ext-epr-time.html
=> expand context (issue #150)

input/pagecontent/index.md
add IP Statements / Cross Version Analysis / Dependency Table / Globals Table
=> #158 and #189

input/resources/structuredefinition/ch-core-composition-epr.xml
=> fix min card for informationRecipient

input/pages/changelog.md, input/resources/namingsystem/ahvn13.xml, input/resources/namingsystem/ber.xml, input/resources/namingsystem/epr-spid.xml, input/resources/namingsystem/gln.xml, input/resources/namingsystem/k.xml, input/resources/namingsystem/nif.xml, input/resources/namingsystem/zsr.xml, input/resources/structuredefinition/ch-core-organization.xml, input/resources/structuredefinition/ch-core-practitioner.xml
see #206
- added the translations for practitioner / organization 
- for the values only english or translations when no english
- removed text narrative manual from naming system
=> improve accronyms definition #206

input/fsh/profiles/CHCorePractitionerRoleEpr.fsh, input/pagecontent/changelog.md
=> PractitionerRole EPR: code binding #222

input/fsh/invariants/ch-addr-1.fsh, input/fsh/invariants/ch-core-hm-1.fsh, input/fsh/invariants/ch-core-hm-2.fsh, input/fsh/invariants/ch-pat-3.fsh, input/pagecontent/changelog.md
=> value instead of valueCoding #225

input/fsh/instances/patient/ElisabethBroennimannByBFH.fsh, input/fsh/invariants/ch-addr-1.fsh, input/fsh/invariants/ch-addr.fsh, input/fsh/profiles/CHCoreAddress.fsh, input/fsh/terminology/ECH007CantonFLAbbreviation.fsh, input/pagecontent/changelog.md
changes see here: https://github.com/hl7ch/ch-core/issues/233#issuecomment-1672875600
@oliveregger could you please review the changes, maybe there is a shorter way to write the constraint
=> Issue233 canton abbreviation

input/fsh/extensions/ResourcesCrossReferences.fsh, input/fsh/instances/bundle/2-ResourceCrossReferencesDokument.fsh
Extension to define a relation of an entry in an document to an other entry in an other document.
=> Extension Entry relationship

input/fsh/invariants/ahvn13-digit-check.fsh, input/fsh/invariants/ahvn13-length.fsh, input/fsh/invariants/ahvn13-startswith756.fsh, input/fsh/invariants/epr-spid-length.fsh, input/fsh/invariants/epr-spid-modulus-10.fsh, input/fsh/invariants/epr-spid-startswith76133761.fsh, input/fsh/invariants/gln.fsh, input/fsh/invariants/veka-length.fsh, input/fsh/invariants/veka-startswith807560.fsh, input/pagecontent/changelog.md
=> warning for gln avn and eprspid constraints #257

input/examples/bundle/CdaContainingOriginalRepresentationAsPdfA.xml, input/pagecontent/changelog.md
https://build.fhir.org/ig/hl7ch/ch-core/branches/issue256/Bundle-CdaContainingOriginalRepresentationAsPdfA.json.html
=> #256 fix references using uuid as fullurl

input/fsh/instances/bundle/2-ResourceCrossReferencesDokument.fsh, input/fsh/instances/organization/GruppenpraxisCH.fsh, input/fsh/instances/patient/MaxMuster.fsh, input/fsh/instances/practitioner/AllzeitBereit.fsh, input/pagecontent/changelog.md
CI Build of the changes: https://build.fhir.org/ig/ralych/ch-core/branches/bugfix-extension-resourcereferencing2/qa.html
=> Fix errors with latest publisher on referencing (#255)

input/fsh/instances/practitioner/AgparMarc.fsh, input/pagecontent/changelog.md
- Practitioner example: https://build.fhir.org/ig/hl7ch/ch-core/branches/issue265_gln-example/Practitioner-AgparMarc.html
- Changelog: https://build.fhir.org/ig/hl7ch/ch-core/branches/issue265_gln-example/changelog.html
=> adapt example to gln rule update #265 (#235)

input/fsh/instances/allergyintolerance/AllergyToCatDander.fsh, input/fsh/instances/condition/Urticaria.fsh, input/fsh/profiles-resources/CHCoreAllergyIntolerance.fsh, input/ignoreWarnings.txt, input/pagecontent/changelog.md
https://build.fhir.org/ig/hl7ch/ch-core/branches/baseProfile_AI/index.html
=> base profiles allergyintolerance #119

input/ignoreWarnings.txt, input/pagecontent/changelog.md
fixed with new version of publisher. 
see no errors in qa: https://build.fhir.org/ig/hl7ch/ch-core/branches/289_displayvalidation/qa.html
=> updates according to #289

input/fsh/profiles-resources/CHCoreCompositionEPR.fsh, input/fsh/profiles-resources/CHCoreCoverage.fsh, input/fsh/profiles-resources/CHCoreEncounter.fsh, input/fsh/profiles-resources/CHCoreImmunization.fsh, input/fsh/profiles-resources/CHCoreOrganization.fsh, input/fsh/profiles-resources/CHCorePatient.fsh, input/fsh/profiles-resources/CHCorePractitioner.fsh, input/pagecontent/changelog.md
https://build.fhir.org/ig/hl7ch/ch-core/branches/306_discriminator/index.html
=> replace deprecated discriminator #306

input/fsh/instances/practitioner/HanspeterWengerByBFH.fsh, input/fsh/invariants/zsh.fsh, input/fsh/profiles-datatypes/Identifier.fsh, input/pagecontent/changelog.md
adds warning according to
https://confluence.sasis.ch/display/PublicZSR/ZSR+Webservice+FAQ
ci-build https://build.fhir.org/ig/hl7ch/ch-core/branches/oe_zsr/qa.html
=> add warning to ZSR #309

expansion-params.json, input/pagecontent/changelog.md, sushi-config.yaml
https://github.com/hl7ch/ch-core/pull/317/files
=> add expansion parameter for sct swiss extension #313

input/pagecontent/changelog.md, sushi-config.yaml
- https://build.fhir.org/ig/hl7ch/ch-core/branches/issue329-terminology/index.html#dependency-table
- https://build.fhir.org/ig/hl7ch/ch-core/branches/issue329-terminology/changelog.html
- https://build.fhir.org/ig/hl7ch/ch-core/branches/issue329-terminology/qa.html#_scratch_repo_fsh-generated_resources_ImplementationGuide-ch.fhir.ig.ch-core
=> terminology dependency #329

input/ignoreWarnings.txt, input/pagecontent/changelog.md, sushi-config.yaml
https://build.fhir.org/ig/hl7ch/ch-core/branches/issue338_pin-canonicals/qa.html
=> Issue 338 pin-canonicals

input/fsh/profiles-resources/CHCoreCondition.fsh, input/fsh/profiles-resources/CHCoreImmunization.fsh, input/pagecontent/changelog.md
* [CH Core Condition](https://build.fhir.org/ig/hl7ch/ch-core/branches/issue346_bindings/StructureDefinition-ch-core-condition.html)
* [CH Core Immunization](https://build.fhir.org/ig/hl7ch/ch-core/branches/issue346_bindings/StructureDefinition-ch-core-immunization.html)
=> add key to additional binding #346

input/fsh/invariants/ch-addr.fsh, input/fsh/invariants/ch-pat-3.fsh, input/pagecontent/changelog.md
=> #315 reduce error to warning

input/fsh/extensions/Author.fsh, input/fsh/extensions/EPRDataEnterer.fsh, input/fsh/extensions/EPRTime.fsh, input/pagecontent/changelog.md
@oliveregger @dvribeira 
do you agree with the proposal i described here: https://github.com/hl7ch/ch-core/issues/363#issuecomment-3252945550
ci build: [extension](https://build.fhir.org/ig/hl7ch/ch-core/branches/363_invalidContext/StructureDefinition-ch-ext-epr-time.html), [qa](https://build.fhir.org/ig/hl7ch/ch-core/branches/363_invalidContext/qa.html#_scratch_repo_fsh-generated_resources_StructureDefinition-ch-ext-epr-time)
=> 363 invalid context
